version: '3.8'

services: 
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
  api:
    image: api
    build: .
    container_name: "api-universe-game"
    command: 
      sh config.sh prod
    ports:
      - '3220:3220'
    volumes:
      - ./dist:/usr/src/api/dist
    links:
      - database      

volumes:
  database:
    driver: local
  api:
    driver: local  
