version: '3.8'

services:
  api:
    image: api
    restart: always
    build: .
    container_name: "api-universe-game"
    command: 
      sh ./start.sh
    ports:
      - '3220:3220'
    volumes:
      - ./dist:/usr/src/api/dist  
    links:
      - database  
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
